### PR TITLE
No error feedback shown,  if list of eligible testakers was not modif…

### PR DESCRIPTION
**Pull request by boajer**
…ied before saving

### CODE REVIEW

**Comment by ssipasseuth** [comment]
Hello @boajer , sorry for the delay on this PR review.
I would need some clarification. Could you define step by step the problem you are trying to solve please ? (I am sure I understand...) Thanks !

**Comment by boajer** [comment]
@ssipasseuth This is very minor issue. If you are as backend admin will open 'Edit Eligibility' popup on testcenter page and then click 'Ok' button without changing any testtakers, you will observe feedback message 'Unknown Error' on the screen, because normal output will be broken by following error 'Warning: strpos() expects parameter 1 to be string, array given in /www/act/tao/helpers/class.Uri.php on line 255'

**Comment by ssipasseuth** [comment]
Sorry, it has been left aside for a while... do you stilll have this issue ? I don't seem to be able to reproduce it anymore...

**Comment by boajer** [comment]
Still reproducible, i've captured small video for you http://goo.gl/K1n91K

**Comment by ssipasseuth** [comment]
Thanks for the video. Strange though I didn't have that issue. But this did fix the issue when saving the eligibility editor with no test taker. It used to save an empty string. Now simply ignore the changes.

**Pull request merged**
