### PR TITLE
Feature/tao 4232 exit button

### PR DESCRIPTION
**Pull request by jsconan**
Related to: https://oat-sa.atlassian.net/browse/TAO-4232

Add a button to exit the proctor monitoring page when the `exitUrl` config is set.

### CODE REVIEW

**Comment by jsconan** [comment]
I added the feature the same way the "Back to session button" was made for the reporting screen. As I was wondering if the button was only related to LTI, I first added it from the proctoring screen.

However as it seems there is no more need from this button outside of the LTI mode, I will close this PR and make the feature as you recommend it.

**Comment by jsconan** [comment]
I reopen the PR because the acceptance criteria need a confirm message, that can only be achieved from the controller of taoProctoring. Also if the branding is not enabled, the exit button won't be displayed.

**Comment by hutnikau** [comment]
I just tried to disable branding and exit button has been successfully rendered.
You can extend taoProctoring js controller for example in this way:
https://github.com/oat-sa/extension-lti-proctoring/compare/develop...experimental/lti_specific_controller?expand=1#diff-d4f049018ec1c3723f17bfa3c047745aR29

This is LTI specific feature and we don't have to change taoProctoring for just to render this button.

**Comment by jsconan** [comment]
Ok, I found another solution. Not by overriding the controller, but by adding an extra controller on LTI.

**Pull request closed without merging**
