### PR TITLE
Feature/bsa 304/update proctoring options translations

### PR DESCRIPTION
**Pull request by rgomeztao**
coming from [BSA-304](https://oat-sa.atlassian.net/browse/TR-4917)

changelog:
* updates FR translations on taoProctoring

[BSA-304]: https://oat-sa.atlassian.net/browse/BSA-304?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by hectoras — APPROVED** [review]
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not `master`
- [x] Target branch is correct
- [x] Commits are following conventional commits
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Kitchen links are not exposed in the description

**Review by shpran — APPROVED** [review]

**Review by jsconan — APPROVED** [review]
It looks good.

image
image
image
image
image


**Review Checklist**
- [ ] ~~New code is covered by tests (if applicable)~~
- [ ] ~~Tests are running successfully (old and new ones) on my local machine (if applicable)~~
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not `master`
- [x] Commits are following [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] Commits messages are meaningful
- [x] Commits are atomic

**Comment by rgomeztao** [comment]
after reading Hans concerns about possible impact in other customers (DEPP) we have decided to move this changes to BOSASELOR extension :). closing

**Comment by rgomeztao** [comment]
Reopening, we will use it to fix some original translation

**Review by hectoras — APPROVED** [review]

**Pull request merged**
